import 'dart:async';

import 'package:flutter/services.dart';


enum AndroidSettingsMenuType {
  ACTION_ACCESSIBILITY_SETTINGS,
  ACTION_ADD_ACCOUNT,
  ACTION_AIRPLANE_MODE_SETTINGS,
  ACTION_APN_SETTINGS,
  ACTION_APPLICATION_DETAILS_SETTINGS,
  ACTION_APPLICATION_DEVELOPMENT_SETTINGS,
  ACTION_APPLICATION_SETTINGS,
  ACTION_APP_NOTIFICATION_SETTINGS,
  ACTION_BATTERY_SAVER_SETTINGS,
  ACTION_BLUETOOTH_SETTINGS,
  ACTION_CAPTIONING_SETTINGS,
  ACTION_CAST_SETTINGS,
  ACTION_CHANNEL_NOTIFICATION_SETTINGS,
  ACTION_DATA_ROAMING_SETTINGS,
  ACTION_DATE_SETTINGS,
  ACTION_DEVICE_INFO_SETTINGS,
  ACTION_DISPLAY_SETTINGS,
  ACTION_DREAM_SETTINGS,
  ACTION_HARD_KEYBOARD_SETTINGS,
  ACTION_HOME_SETTINGS,
  ACTION_IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS,
  ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS,
  ACTION_INPUT_METHOD_SETTINGS,
  ACTION_INPUT_METHOD_SUBTYPE_SETTINGS,
  ACTION_INTERNAL_STORAGE_SETTINGS,
  ACTION_LOCALE_SETTINGS,
  ACTION_LOCATION_SOURCE_SETTINGS,
  ACTION_MANAGE_ALL_APPLICATIONS_SETTINGS,
  ACTION_MANAGE_APPLICATIONS_SETTINGS,
  ACTION_MANAGE_DEFAULT_APPS_SETTINGS,
  ACTION_MANAGE_OVERLAY_PERMISSION,
  ACTION_MANAGE_UNKNOWN_APP_SOURCES,
  ACTION_MANAGE_WRITE_SETTINGS,
  ACTION_MEMORY_CARD_SETTINGS,
  ACTION_NETWORK_OPERATOR_SETTINGS,
  ACTION_NFCSHARING_SETTINGS,
  ACTION_NFC_PAYMENT_SETTINGS,
  ACTION_NFC_SETTINGS,
  ACTION_NIGHT_DISPLAY_SETTINGS,
  ACTION_NOTIFICATION_LISTENER_SETTINGS,
  ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS,
  ACTION_PRINT_SETTINGS,
  ACTION_PRIVACY_SETTINGS,
  ACTION_QUICK_LAUNCH_SETTINGS,
  ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,
  ACTION_REQUEST_SET_AUTOFILL_SERVICE,
  ACTION_SEARCH_SETTINGS,
  ACTION_SECURITY_SETTINGS,
  ACTION_SETTINGS,
  ACTION_SHOW_REGULATORY_INFO,
  ACTION_SOUND_SETTINGS,
  ACTION_SYNC_SETTINGS,
  ACTION_USAGE_ACCESS_SETTINGS,
  ACTION_USER_DICTIONARY_SETTINGS,
  ACTION_VOICE_CONTROL_AIRPLANE_MODE,
  ACTION_VOICE_CONTROL_BATTERY_SAVER_MODE,
  ACTION_VOICE_CONTROL_DO_NOT_DISTURB_MODE,
  ACTION_VOICE_INPUT_SETTINGS,
  ACTION_VPN_SETTINGS,
  ACTION_VR_LISTENER_SETTINGS,
  ACTION_WEBVIEW_SETTINGS,
  ACTION_WIFI_IP_SETTINGS,
  ACTION_WIFI_SETTINGS,
  ACTION_WIRELESS_SETTINGS,
  ACTION_ZEN_MODE_PRIORITY_SETTINGS
}

class AndroidSettingsMenu {
  static const MethodChannel _channel =
      const MethodChannel('com.dowen.android_settings_menu');

  static Future<String> get platformVersion async {
    final String version = await _channel.invokeMethod('getPlatformVersion');
    return version;
  }
  static Future<dynamic> checkMenu(AndroidSettingsMenuType type) async {
    return await _channel.invokeMethod("setting.checkMenu", {"name": type.toString().substring(type.toString().indexOf('.')+1)});
  }

  static Future<dynamic> openMenu(AndroidSettingsMenuType type) async {
    return await _channel.invokeMethod("setting.openMenu", {"name": type.toString().substring(type.toString().indexOf('.')+1)});
  }
}
